#!/usr/bin/env bash
# ==============================================================================
# download_cosmopower_models.sh
# ==============================================================================
# Fetch CosmoPower TT/TE/EE neural-network emulators into
# gpu_validation/phase2/models/. These are required by Phase 2 MCMC runs.
#
# Source: Zenodo record 19741059 (DOI 10.5281/zenodo.19741059), deposited
# alongside the MTDF source release. Each file is fetched directly from the
# record and verified against the SHA-256 recorded below.
#
# At runtime, cosmopower_setup.py loads the .npz variants (the .pkl variants
# exist only for legacy TensorFlow <2.20 compatibility and are not required).
#
# Provenance and licence note:
#   * These .npz emulator cache files are generated by training CosmoPower
#     (Spurio Mancini et al. 2022) on CLASS spectra. They are redistributed
#     here only as MTDF reproducibility artefacts.
#   * They inherit the reuse conditions of the CosmoPower-derived workflow:
#     CosmoPower is published under GPL-3 with an additional non-commercial
#     research-use condition per its upstream repository. Users of these
#     emulator files must honour those conditions unless a separate licence
#     is explicitly granted.
#   * Please cite CosmoPower (Spurio Mancini et al. 2022) in any scientific
#     work that uses these files, and preserve any third-party licence
#     notices that accompany the upstream codebase.
#   * See THIRD_PARTY_NOTICES.md for the complete attribution list.
# ==============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
ZENODO_RECORD_ID="19741059"
ZENODO_DOI="10.5281/zenodo.19741059"
ZENODO_BASE="https://zenodo.org/records/${ZENODO_RECORD_ID}/files"

# Each entry: "filename|sha256|download_url"
declare -a MANIFEST=(
  "TT_v1.npz|3cb314678966c1377f9306760a0b9df12058f7896e8064475982c7ebf4cd4a84|${ZENODO_BASE}/TT_v1.npz?download=1"
  "TE_v1.npz|3c58c4f21e04f6c98a35ade6e774eefba57bfb1ea70f7ff025aec14b2020bb73|${ZENODO_BASE}/TE_v1.npz?download=1"
  "EE_v1.npz|299d05e29a4d9db5fdfd9671e0081c6fac517624057a9a23687a02ddb2ab6424|${ZENODO_BASE}/EE_v1.npz?download=1"
)

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="${REPO_ROOT}/gpu_validation/phase2/models"

mkdir -p "${TARGET_DIR}"

echo "Fetching CosmoPower emulators from Zenodo record ${ZENODO_RECORD_ID}"
echo "  DOI: ${ZENODO_DOI}"
echo "  Target: ${TARGET_DIR}"
echo

for entry in "${MANIFEST[@]}"; do
  IFS='|' read -r fname expected_sha url <<<"${entry}"
  out="${TARGET_DIR}/${fname}"

  if [[ -f "${out}" ]]; then
    actual_sha=$(sha256sum "${out}" | awk '{print $1}')
    if [[ "${actual_sha}" == "${expected_sha}" ]]; then
      echo "[ok]    ${fname} already present, SHA-256 verified"
      continue
    fi
    echo "[warn]  ${fname} present but SHA-256 mismatch, re-downloading"
    rm -f "${out}"
  fi

  echo "[fetch] ${fname}"
  curl --fail --location --progress-bar -o "${out}" "${url}"

  actual_sha=$(sha256sum "${out}" | awk '{print $1}')
  if [[ "${actual_sha}" != "${expected_sha}" ]]; then
    echo "[fail]  ${fname}: SHA-256 mismatch after download" >&2
    echo "         expected: ${expected_sha}" >&2
    echo "         actual:   ${actual_sha}" >&2
    rm -f "${out}"
    exit 1
  fi
  echo "[ok]    ${fname} SHA-256 verified"
done

echo
echo "All CosmoPower emulators fetched into:"
echo "  ${TARGET_DIR}"
